
services:
  node-app:
    build: .
    volumes:
      - ./src:/app/src:ro
    container_name: node-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  # mongo:
  #   image: mongo:latest
  #   restart: always
  #   volumes:
  #     - mongo-db:/data/db
  #   container_name: mongo
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: aelmahdi13
  #     MONGO_INITDB_ROOT_PASSWORD: aHMEDO1063114260

  # mongo-express:
  #   image: mongo-express:latest
  #   restart: always
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: "aelmahdi13"
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: "aHMEDO1063114260"
  #     ME_CONFIG_MONGODB_URL: "mongodb://aelmahdi13:aHMEDO1063114260@mongo:27017/"
  #     ME_CONFIG_BASICAUTH_USERNAME: "admin" # هذا للدخول لصفحة الويب نفسها
  #     ME_CONFIG_BASICAUTH_PASSWORD: "pass"  # يمكنك تغييره كما تحب
  #   depends_on:
  #     - mongo
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1231
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    container_name: postgres

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    container_name: redis

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app


volumes:
  mongo-db: 
  postgres-db: